server:
  port: 8001

spring:
  application:
    name: api-gateway
  config:
    import: optional:file:.env[.properties]
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-rote # AUTH MICROSERVICE ROUTING
          uri: lb://auth
          predicates:
            - Path=/api/v1/auth/**
            - Method=POST,GET
        - id: bpmn-route  # BPMN MICROSERVICE ROUTING
          uri: lb://bpmn
          predicates:
            - Path=/api/v1/bpmn/**
            - Method=POST,GET
        - id: charity-rote # CHARITY MICROSERVICE ROUTING
          uri: lb://charity
          predicates:
            - Path=/api/v1/charity/**
            - Method=POST,GET
        - id: chat-rote # CHAT MICROSERVICE ROUTING
          uri: lb://chat
          predicates:
            - Path=/api/v1/chat/**
            - Method=POST,GET
        - id: core-rote # CORE MICROSERVICE ROUTING
          uri: lb://core
          predicates:
            - Path=/api/v1/core/**
            - Method=POST,GET,DELETE,PUT

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    urls:
#      - url: /gateway/v1/api-docs
#        name: api-gateway
#      - url: /auth/v1/api-docs
#        name: auth-microservice

security:
  jwt:
    secret: ${JWT_SECRET}