server:
  port: 8001

spring:
  application:
    name: api-gateway
  config:
    import: optional:file:.env[.properties]
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

