server:
  port: 8002

api:
  version: /api/v1

spring:
  application:
    name: auth
  config:
    import: optional:file:.env[.properties]

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

rest:
  userServiceLink: ${USER_SERVICE_LINK}

security:
  jwt:
    secret: ${JWT_SECRET}
    access: 1
    refresh: 30
