server:
  port: 8002

api:
  version: /api/v1

spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    virtual-host: vhost
  application:
    name: auth
  config:
    import: optional:file:.env[.properties]

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

rest:
  userServiceLink: ${USER_SERVICE_LINK}

security:
  jwt:
    secret: ${JWT_SECRET}
    access: 1
    refresh: 30

#openapi:
#  service:
#    title: Auth-microservice docs
#    version: 1.0.0
#    url: http://localhost:8001
#springdoc:
#  api-docs:
#    path: /auth/v1/api-docs
#  swagger-ui:
#    path: /api/v1/auth/swagger-ui.html
