server:
  port: 8004

spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    virtual-host: /
  application:
  main:
    name: chat
    web-application-type: none
  config:
    import: optional:file:.env[.properties]

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

crud:
  microservice:
    url: http://core:8003