server:
  port: 8003

spring:
  application:
    name: core
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
#  flyway:
#    url: jdbc:postgresql://localhost:5432/postgres
#    user: postgres
#    password: postgres
#    locations: classpath:db/migration

minio:
  url: ${MINIO_URL}
  profileBucket: ${MINIO_BUCKET_PROFILE}
  postBucket: ${MINIO_BUCKET_POST}
  messageBucket: ${MINIO_BUCKET_MESSAGE}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
#  instance:
#    instance-id: ${spring.application.name}:${random.uuid}
#    prefer-ip-address: true