server:
  port: 8009

spring:
  application:
    name: eureka-server
  config:
    import: optional:file:.env[.properties]

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URL}



